[platformio]
default_envs = octopus_pro_f446
src_dir = src
include_dir = include

[env:octopus_pro_f446]
platform = ststm32
board = genericSTM32F446ZE
framework = arduino
board_build.mcu = stm32f446zet6
board_build.f_cpu = 180000000L

; Yerel USB-FS CDC yapılandırması (12 Mbps doğrudan RPi bağlantısı)
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D USBD_USE_CDC
    -D USB_MANUFACTURER=\"LaserRunner\"
    -D USB_PRODUCT=\"LaserRunner_Octopus_Pro\"
    -D HAL_PCD_MODULE_ENABLED
    -O3
    -Wall

upload_protocol = dfu
monitor_speed = 115200
